name: Notify Discord on Main Branch Changes

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE=$(jq -n --arg msg "New commit to the main branch!" --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" '{
            embeds: [{
              title: "New Commit to Main Branch",
              description: $msg,
              url: $url,
              color: 5814783,
              fields: [
                {
                  name: "Repository",
                  value: $GITHUB_REPOSITORY
                },
                {
                  name: "Commit",
                  value: $GITHUB_SHA
                }
              ]
            }]
          }')
          curl -H "Content-Type: application/json" -d "$MESSAGE" "$DISCORD_WEBHOOK_URL"
