name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH connection
        run: |
          echo "Attempting SSH connection to ${{ secrets.SERVER_IP }} as ${{ secrets.SSH_USER }}"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd public_html/andrewcromar/home
            git pull origin main
            git config user.email "your_email@example.com"
            git config credential.helper store
            echo "${{ secrets.GIT_PAT }}" | git credential approve
